# Generated by Django 4.2.10 on 2025-06-08 09:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField()),
                ('teacher', models.CharField(max_length=256)),
                ('total_slots', models.PositiveIntegerField()),
                ('available_slots', models.PositiveIntegerField()),
                ('fees', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=256)),
                ('client_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('booking_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='baseApp.fitnessclass')),
            ],
        ),
    ]
