# Generated by Django 4.2.10 on 2025-06-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='available_slots',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
